FROM node:alpine as base

ENV DIR /usr/src/app
WORKDIR $DIR

FROM base as dev

COPY package*.json $DIR
COPY tsconfig*.json $DIR
COPY src $DIR/src

RUN apk add --no-cache bash

RUN npm install

CMD [ "npm", "run", "dev" ]

FROM base AS build

RUN apk update && apk add --no-cache dumb-init

COPY package*.json $DIR
RUN npm install

COPY tsconfig*.json $DIR
COPY src $DIR/src

RUN npm run build && \
    npm prune --production

FROM base AS production

ENV USER=node

COPY --from=build /usr/bin/dumb-init /usr/bin/dumb-init
COPY --from=build $DIR/node_modules $DIR/node_modules
COPY --from=build $DIR/dist $DIR/dist

USER $USER

CMD ["dumb-init", "node", "dist/index.js"]


