services:
  server:
    build:
      context: .
    # env_file:
    #   - .env
    # environment:
      # NODE_ENV: production
      # PORT: 3000
      # MYSQL_HOST: db
    volumes:
      - ./:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    ports:
      - 3000:3000
    depends_on:
      - db
      # db:
        # condition: service_healthy
    networks:
      - project_network
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: "fsd-typeorm"
      MYSQL_ROOT_PASSWORD: "1234"
    networks:
      - project_network
    # healthcheck:
    #   test: mysqladmin ping -h 127.0.0.1
    #   start_period: 5s
    #   interval: 5s
    #   timeout: 5s
    #   retries: 55
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db:
  node_modules:

networks:
  project_network: